from django.conf import settings

CELERY_BROKER_URL = f'{settings.REDIS_PORT_URL}/0'
CELERY_RESULT_BACKEND = f'{settings.REDIS_PORT_URL}/1'

CELERY_TIMEZONE = "Asia/Tashkent"
CELERY_TASK_TRACK_STARTED = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_BEAT_SCHEDULE = {

}