services:

  app:
    build:
        context: .
        dockerfile: docker/dev/Dockerfile
    container_name: app
    command:
      sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    volumes:
      - "../../src:/app"
    depends_on:
      - postgres_db
      - redis_db

  postgres_db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - ../../.env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_db:
    image: redis:7.0.15
    container_name: redis_db
    ports:
      - "6378:6379"
    restart: always
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    env_file:
      - ../../.env
    volumes:
      - "../../src:/app"
    depends_on:
      - app
      - redis_db

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    volumes:
      - "../../src:/app"
    depends_on:
      - app
      - redis_db
      - celery_worker


volumes:
  postgres_data:
  redis_data:

