services:

  app:
    build:
        context: ../../
        dockerfile: docker/prod/Dockerfile
    image: catering-app:latest
    container_name: app
    command:
      sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    environment:
      - ENV=production
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    volumes:
      - "../../src:/app"
    depends_on:
      - postgres_db
      - redis_db

  postgres_db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - ../../.env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_db:
    image: redis:7.0.15
    container_name: redis_db
    ports:
      - "6378:6379"
    restart: always
    volumes:
      - redis_data:/data

  celery_worker:
    build:
        context: ../../
        dockerfile: docker/prod/Dockerfile
    image: catering-worker:latest
    command: celery -A config worker --loglevel=info
    environment:
      - ENV=production
    env_file:
      - ../../.env
    volumes:
      - "../../src:/app"
    depends_on:
      - app
      - redis_db

  celery_beat:
    build:
        context: ../../
        dockerfile: docker/prod/Dockerfile
    images: catering-beat:latest
    command: celery -A config beat --loglevel=info
    environment:
      - ENV=production
    env_file:
      - ../../.env
    volumes:
      - "../../src:/app"
    depends_on:
      - app
      - redis_db
      - celery_worker


volumes:
  postgres_data:
  redis_data:
