name: Deploy to AWS VM

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_DEVELOPMENT_SSH_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-86-124-254.compute-1.amazonaws.com '
            cd /home/ubuntu/Catering
            git pull origin main
            docker system prune -f
            docker-compose -f docker/prod/docker-compose.prod.yaml down
            docker-compose -f docker/prod/docker-compose.prod.yaml up -d --build
            exit
          '
